### PR TITLE
Broken if statement

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**

### CODE REVIEW

**Comment by taylortom** [comment]
+1, Good spot.

**Comment by moloko** [comment]
it's probably something in package.json's devDependecies. Have a look at the [version in contrib-hotgraphic](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/package.json), that should be OK as that got successfully merged quite recently

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
